// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnXIcY61kFcbWK6pjFgHyRCfu2Tni6SkE',
    appId: '1:1569540045:ios:14d97414f7987ad18ca684',
    messagingSenderId: '1569540045',
    projectId: 'padeltid-85e2b',
    storageBucket: 'padeltid-85e2b.appspot.com',
    iosBundleId: 'com.example.flutterAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVwgqZ2E6LiUQB-zsniLA4EnUm781zs88',
    appId: '1:1569540045:web:c06c7f452572a0948ca684',
    messagingSenderId: '1569540045',
    projectId: 'padeltid-85e2b',
    authDomain: 'padeltid-85e2b.firebaseapp.com',
    storageBucket: 'padeltid-85e2b.appspot.com',
    measurementId: 'G-6SRZ7SK2BE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVwgqZ2E6LiUQB-zsniLA4EnUm781zs88',
    appId: '1:1569540045:web:c06c7f452572a0948ca684',
    messagingSenderId: '1569540045',
    projectId: 'padeltid-85e2b',
    authDomain: 'padeltid-85e2b.firebaseapp.com',
    storageBucket: 'padeltid-85e2b.appspot.com',
    measurementId: 'G-6SRZ7SK2BE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnXIcY61kFcbWK6pjFgHyRCfu2Tni6SkE',
    appId: '1:1569540045:ios:14d97414f7987ad18ca684',
    messagingSenderId: '1569540045',
    projectId: 'padeltid-85e2b',
    storageBucket: 'padeltid-85e2b.appspot.com',
    iosBundleId: 'com.example.flutterAndroid',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatfswF6FpDuRo5_hA3_IjKxzz2NOlZKs',
    appId: '1:1569540045:android:c63ec2db84205be38ca684',
    messagingSenderId: '1569540045',
    projectId: 'padeltid-85e2b',
    storageBucket: 'padeltid-85e2b.appspot.com',
  );

}