name: Flutter Web Deploy
on:
  push:
    branches:
      - master
jobs:
  build:    
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      
      # Generate Firebase config
      - name: Generate Firebase Configuration
        run: dart run scripts/prepare_firebase.dart
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      
      - run: flutter build web --release --dart-define=Dart2jsOptimization=O4 --base-href /
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh-pages --force
